version: '3.8'

services:
  web:
    build: .
    container_name: hoplife_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: hoplife_keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak_data:/opt/keycloak/data
      - ./keycloak-config:/opt/keycloak/data/import
      - ./keycloak-page:/opt/keycloak/themes/hoplife