site_name: HopLife

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand

docs_dir: zdocs

nav:
  - Home: index.md
  - Documento de Visão: visao.md
  - Documento de Arquitetura: arquitetura.md
  - PEP 8: PEP8.md