# Generated by Django 6.0.5 on 2026-06-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_perfilusuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='assistencia_motora_ativa',
            field=models.BooleanField(default=False, verbose_name='Ativar Assistência Motora'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tamanho_botao',
            field=models.CharField(choices=[('normal', 'Normal'), ('largo', 'Largo')], default='normal', max_length=10, verbose_name='Tamanho dos Botões'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tamanho_texto',
            field=models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], default='medio', max_length=10, verbose_name='Tamanho do Texto'),
        ),
    ]
