# Generated by Django 6.0.5 on 2026-06-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_perfilusuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='tamanho_botao',
            field=models.CharField(choices=[('normal', 'Normal'), ('largo', 'Largo')], default='normal', max_length=15),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tamanho_texto',
            field=models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], default='medio', max_length=15),
        ),
    ]
