# Generated by Django 6.0.5 on 2026-06-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfilusuario_tamanho_botao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='assistencia_motora',
            field=models.BooleanField(default=False, help_text='Ativa a proteção contra cliques rápidos (tremores) e o clique por permanência.'),
        ),
    ]
