# Generated by Django 6.0.5 on 2026-06-18 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilGamificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia_dias_ativos', models.PositiveIntegerField(default=0)),
                ('maior_sequencia_historica', models.PositiveIntegerField(default=0)),
                ('ultima_interacao', models.DateField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_gamificacao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
