# Generated by Django 6.0.5 on 2026-06-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraseInspiradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='A frase que vai aparecer para o usuário.')),
                ('autor', models.CharField(blank=True, help_text='Nome do autor da frase.', max_length=100)),
            ],
            options={
                'verbose_name': 'Frase Inspiradora',
                'verbose_name_plural': 'Frases Inspiradoras',
            },
        ),
    ]
