# Generated by Django 6.0.5 on 2026-06-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0002_categoria_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodiario',
            name='nota',
            field=models.TextField(blank=True, null=True, verbose_name='Nota do dia'),
        ),
    ]
